-- Rename columns if they exist
ALTER TABLE quiz ALTER COLUMN quiz_config RENAME TO quiz_name;
ALTER TABLE quiz ALTER COLUMN questions RENAME TO questions_list;

-- Add new columns if they do not already exist
ALTER TABLE quiz ADD COLUMN IF NOT EXISTS created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE quiz ADD COLUMN IF NOT EXISTS updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE quiz ADD COLUMN IF NOT EXISTS user_created VARCHAR(255);
ALTER TABLE quiz ADD COLUMN IF NOT EXISTS user_updated VARCHAR(255);
ALTER TABLE quiz ADD COLUMN IF NOT EXISTS quiz_version BIGINT DEFAULT 1;
ALTER TABLE quiz ADD COLUMN IF NOT EXISTS is_private BOOLEAN DEFAULT FALSE;